// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9PXfeeErhshH8WH8N8fYRlUxEKz_sYTA',
    appId: '1:736490329918:web:5ed8ccc6bee395af2ebe6f',
    messagingSenderId: '736490329918',
    projectId: 'e-commerce-153cc',
    authDomain: 'e-commerce-153cc.firebaseapp.com',
    storageBucket: 'e-commerce-153cc.firebasestorage.app',
    measurementId: 'G-5B294HPH7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJr6pcN-5wdT4-4pJgm-k_dtbS0npd0Co',
    appId: '1:736490329918:android:b195e69e02d9c6192ebe6f',
    messagingSenderId: '736490329918',
    projectId: 'e-commerce-153cc',
    storageBucket: 'e-commerce-153cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhWMUIXtL71c6llRc5lloQ9ZAkaotJaSA',
    appId: '1:736490329918:ios:6dd02f491078a5f62ebe6f',
    messagingSenderId: '736490329918',
    projectId: 'e-commerce-153cc',
    storageBucket: 'e-commerce-153cc.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhWMUIXtL71c6llRc5lloQ9ZAkaotJaSA',
    appId: '1:736490329918:ios:6dd02f491078a5f62ebe6f',
    messagingSenderId: '736490329918',
    projectId: 'e-commerce-153cc',
    storageBucket: 'e-commerce-153cc.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9PXfeeErhshH8WH8N8fYRlUxEKz_sYTA',
    appId: '1:736490329918:web:73040ce0e3aded0f2ebe6f',
    messagingSenderId: '736490329918',
    projectId: 'e-commerce-153cc',
    authDomain: 'e-commerce-153cc.firebaseapp.com',
    storageBucket: 'e-commerce-153cc.firebasestorage.app',
    measurementId: 'G-3SZXL6JDPG',
  );
}
